### ISSUE TITLE
System tray support

### ISSUE THREAD

**Issue by Victor239** [flathub/com.dec05eba.gpu_screen_recorder#104]
Since I only use Replay mode it makes sense for this kind of app to stay in the background open whilst being accessible from the system tray, instead of as a permanently open window.

**Comment by dec05eba** [comment]
I have considered that but some users (including me myself) dont have a systray and gnome doesn't have one either (?). Maybe it could be done if there is a check if the user has a systray.

**Comment by dec05eba** [comment]
but anyways, this is the wrong place to write this. This should follow this: https://github.com/flathub/com.dec05eba.gpu_screen_recorder/issues/6

**Comment by Victor239** [comment]
Okay sorry for posting this in the wrong place. 

I'm trying to use your recommended CLI method but I'm having issues saving the file. I see `ALT + F9` saving keybinding doesn't work so I did `CTRL + C` but that didn't work either. Here's the initial logs from running the command:
```
flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w eDP-1 -f 60 -c mp4 -r 30 -a "$(pactl get-default-sink).monitor" -o "$HOME/Videos/Replays"
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
[hevc_vaapi @ 0x5607da055cc0] ignoring invalid SAR: 0/0
[hevc_vaapi @ 0x5607da055cc0] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
Info: using hevc encoder because a codec was not specified
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[hevc_vaapi @ 0x5607da055cc0] ignoring invalid SAR: 0/0
[hevc_vaapi @ 0x5607da055cc0] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
update fps: 245
update fps: 246
update fps: 246
update fps: 244
```

And when I do `CTRL + C`:
```
update fps: 247
update fps: 246
^C
boss@boss-XPS:~/Documents/ESSENTIALS$ kms server info: kms client shutdown, shutting down the server
```
And it gets stuck there. Doing `CTRL + C` exits it completely but nothing gets saved.

**Comment by dec05eba** [comment]
The way to use that is documented here: https://git.dec05eba.com/gpu-screen-recorder/about/
in your case when using replay mode, just run `killall -SIGUSR1 gpu-screen-recorder` and it will save a replay. You can bind this command to a key in your desktop environment.
