### ISSUE TITLE
exact needed filesystem permissions?

### ISSUE THREAD

**Issue by boredsquirrel** [flathub/com.dec05eba.gpu_screen_recorder#117]
the app does not work when removing `host:rw` filesystem permissions.

What exact directories is required?

**Comment by dec05eba** [comment]
When you select the directory to save to that gives the application access to that directory without any special permissions, but the recording application is a separate binary that runs as a child process and flatpak doesn't support sharing permissions with child processes. That means full host:rw filesystem permission is required.

**Comment by boredsquirrel** [comment]
hmm, it didnt use a portal for saving, it used a normal GTK filepicker and only showed the directory that I gave it access to.

You know what you do, so I suppose this issue cannot be solved?

**Comment by dec05eba** [comment]
Yeah it cant be solved unless flatpak makes it possible to share permissions with child processes or unless I put the programs into the same process, but I cant do that right now because of nvidia driver bugs that makes the process freeze when you stop recording.

**Comment by boredsquirrel** [comment]
thanks for the explanation!
