### ISSUE TITLE
[Feature request] Window capture under wayland?

### ISSUE THREAD

**Issue by Reonu** [flathub/com.dec05eba.gpu_screen_recorder#124]
Hi, thanks for making this program :)

I'm just wondering whether window capture under Wayland is a planned feature or if it's just an inherent Wayland limitation that can never be addressed.

**Comment by dec05eba** [comment]
Desktop portal + pipewire capture is planned and when that is implemented window capture on wayland will work as well, assuming your wayland compositor of choice supports it.
