### ISSUE TITLE
Can't use on an Optimus laptop with Wayland

### ISSUE THREAD

**Issue by Reonu** [flathub/com.dec05eba.gpu_screen_recorder#126]
Hey!

So I've been loving this software on my desktop PC but I'm trying to also use it on my laptop and running into an issue.

I'm running wayland and using envy-control to use my laptop in Nvidia-only mode. But when I launch gpu-screen-recorder-gtk (again, in Nvidia only mode) it says "running on Intel" and it throws an error that H264/HEVC recording isn't available on my system. I can't seem to get it to run on my Nvidia GPU, despite the fact that my system is set to Nvidia only.

It was fine on X11 iirc, the issue seems to present itself on Wayland only.

It's an MSI GE65 Raider 9SF with an RTX 2070.

I'm using the AUR package.

How can I make it work? Thanks!

**Comment by Reonu** [comment]
Just realized that I'm not supposed to report issues in this repo. Closing this and putting it in the correct repo. Sorry

**Comment by dec05eba** [comment]
It's a flatpak specific issue likely so its ok if its here.

**Comment by dec05eba** [comment]
If you are really running under nvidia on your system then it's likely a flatpak specific issue. Try running `flatpak update` to see if that fixes it.
To test if you are really running under nvidia can you run `eglinfo > log.txt` and upload that file here. Then run `flatpak install flathub io.github.arunsivaramanneo.GPUViewer` and launch GPU-Viewer take a screenshot of the the OpenGL tab.

But recording on intel should work on your system. Can you try running `flatpak install org.freedesktop.Platform.VaInfo/x86_64/23.08` and then `flatpak run org.freedesktop.Platform.VaInfo` and post the output here?

**Comment by dec05eba** [comment]
Oh sorry just saw now that you use the aur package. Yeah that should be in the other issues repository.
