### ISSUE TITLE
Giving root access to a user installed package

### ISSUE THREAD

**Issue by madness742** [flathub/com.dec05eba.gpu_screen_recorder#130]
Hi! 

Is it possible to give root permission to the flathub package when installed as user, as opposed to system-wide? Due to [this](https://bugs.kde.org/show_bug.cgi?id=466559) bug I rather not install it system-wide.

Thought I'd ask first before attempting to compile the package. :)

**Comment by dec05eba** [comment]
It's technically possible but there are issues with doing that reliably (and also security issue). Im already tracking this as an issue which I might solve one day, but I have added desktop portal capture support and in that case root access wont be necessary to record your monitor (or when recording on wayland) but the update hasn't been pushed to flathub yet.

**Comment by madness742** [comment]
Thank you, I'm looking forward to the update!
