### ISSUE TITLE
Update runtime to Freedesktop 24.08

### ISSUE THREAD

**Issue by x80486** [flathub/com.dec05eba.gpu_screen_recorder#153]

**Comment by dec05eba** [comment]
Do most flatpaks use 24.08?

**Comment by x80486** [comment]
I don't have any stats, but all the ones that I maintain are upgraded — and some others that I use, I've been creating issues for them to be aware.

**Comment by dec05eba** [comment]
Ok

**Comment by bbhtt** [comment]
> Unrelated, but I think you don't need --talk-name=org.freedesktop.Notifications anymore — but wait for @bbhtt to confirm.

If you use libnotify for notifications that permission is not needed anymore.
