### ISSUE TITLE
gsr error:your opengl environment is not properly setup. It's using llvmpipe (software rendering) for opengl instead of your graphics card. Please make sure your graphics driver is properly installed

### ISSUE THREAD

**Issue by Al3x-and3r** [flathub/com.dec05eba.gpu_screen_recorder#67]
I'm running the latest version of Ubuntu (Lubuntu). I am using recent driver version 535 for my RTX 2080 graphics card. Even though I am using my graphics card for the renderer as it shows in this screenshot below, it says I am still usling llvmpipe? I have reinstalled the driver, and the same issue is present.
![asdasd](https://github.com/flathub/com.dec05eba.gpu_screen_recorder/assets/142016824/db519cf0-2e97-4e57-8c3a-1cf55e7db93b)

![screen01](https://github.com/flathub/com.dec05eba.gpu_screen_recorder/assets/142016824/29039104-2d2a-4bd2-9bc1-3a2e51f7778c)

**Comment by dec05eba** [comment]
show output of eglinfo instead of glxinfo. gpu screen recorder uses egl, not glx.

**Comment by Al3x-and3r** [comment]
![screen04](https://github.com/flathub/com.dec05eba.gpu_screen_recorder/assets/142016824/ab6c8527-aa59-41f7-83ab-dd46ad928180)

**Comment by dec05eba** [comment]
It might then be an issue in your flatpak environment. Try running this: https://flathub.org/apps/io.github.arunsivaramanneo.GPUViewer to see if egl is running under nvidia in flatpak

**Comment by Al3x-and3r** [comment]
![screen05](https://github.com/flathub/com.dec05eba.gpu_screen_recorder/assets/142016824/8f59d576-4337-4d50-83b9-6a01dd55cc8e)

It looks to me like it is.

**Comment by dec05eba** [comment]
How do you launch gpu screen recorder flatpak?

**Comment by Al3x-and3r** [comment]
I use this command: "flatpak run com.dec05eba.gpu_screen_recorder". However, it now works with no error. I don't know what that was about.
![screen06](https://github.com/flathub/com.dec05eba.gpu_screen_recorder/assets/142016824/50fb6b51-0b53-4739-bf0e-9bca74729d3b)

**Comment by dec05eba** [comment]
Maybe flatpak installed the proper things when you installed GPUViewer. Did it install anything else when you installed it?

**Comment by Al3x-and3r** [comment]
This might be the case, is there a command to check what was recently installed so I can check this out?

**Comment by dec05eba** [comment]
I dont know if there is a way to display packages like that, but anyways good. Can you just verify if recording also works? the recording is a separate program that is launched when you start recording.

**Comment by Al3x-and3r** [comment]
It works, I tested out the recording feature and was able to view it afterwards. No issue.

As for the GPUViewer dependencies, not sure if any of these made it work: python, vulkan-tools,clinfo, es2_info

**Comment by dec05eba** [comment]
Thanks, it might be es2. I'll see if i can fix it.
