### ISSUE TITLE
Doesnt capture the cursor on Wayland with NVIDIA

### ISSUE THREAD

**Issue by alex285** [flathub/com.dec05eba.gpu_screen_recorder#89]
Cursor is invisible on Wayland session (GNOME 45)

**Comment by dec05eba** [comment]
I see. Until very recently nvidia didn't support a separate cursor so I didn't add support for that yet. I'll add support for that soon.

**Comment by dec05eba** [comment]
Btw, which distro are you using? since its nvidia driver version specific and very specific gnome version that this would happen with

**Comment by dec05eba** [comment]
I tried to run gnome 45 wayland on arch linux on my nvidia gtx 1080 and it freezes my computer, so unfortunately I cant test this.. kde plasma wayland works but it doesn't use hardware cursors yet

**Comment by dec05eba** [comment]
I managed to test it by using kde plasma 6 rc
