### ISSUE TITLE
~/.local/bin directory permission denied error, reason kms-server-proxy

### ISSUE THREAD

**Issue by Scotty-Trees** [flathub/com.dec05eba.gpu_screen_recorder#97]
Greetings,

Been using this lovely flatpak app for a while, saw a few recent updates via flathub which I have installed and currently using v3.5.2 of GPU screen recorder. However, the latest version there is an issue. As mentioned here: https://discussion.fedoraproject.org/t/i-dont-own-permissions-to-local-bin-whats-going-on/105409/6 there appears to be an issue with permissions as GPU screen recorder, "it intentionally [installs itself as root](https://git.dec05eba.com/kms-server-proxy/tree/main.c#n142) in that directory, which seems a bit broken." It was suggested to open an issue here to help fix this issue. Please let me know if you need any further information I'd be happy to provide. Also to mention, I first only noticed this error when I used Pika Backup to update my system, and I got an error saying it was unable to backup my ~/.local/bin directory, which was not a problem before the recent GPU screen recorder updates.

**Comment by dec05eba** [comment]
Hi, one part of this is intentional (creating the file with root as owner), however creating ~/.local/bin when it doesn't exist as root is not intentional so I'll fix it. Thanks.

**Comment by Scotty-Trees** [comment]
Thanks for the quick reply and appreciate the fix for the issue, glad it was an easy one to address. And thanks very much for making and updating GPU screen recorder btw, it works amazing on Fedora Gnome on Wayland.

**Comment by dec05eba** [comment]
Note that this update wont change the permission of the existing ~/.local/bin, it will only prevent this issue from happening again. For users that didn't already have ~/.local/bin and it was created with incorrect permissions by gpu screen then they will have to run `sudo chown $USER:$USER ~/.local/bin` to change the owner of that directory to the current user.

**Comment by superuser-miguel** [comment]
@dec05eba Are you using xdg-desktop-Portals in any way? Why the requirement for a root user file? Just out of curiosity.

**Comment by dec05eba** [comment]
It's not using desktop portal. The reason its using this setup is a workaround for not being able to use setcap inside flatpak sandbox and to prevent flatpak program update from overwriting the setcap capability that was previously done. It's an ugly hack, but this is the only way to have fully hardware accelerated screen recording work on x11 and wayland (on amd/intel, and properly on all nvidia setups, and with hdr support as well) inside a flatpak without having a password prompt showing every time you want to record.

I eventually want to add the option to start instant replay on system startup so you can press a key at any time to save a replay which is a feature that users have asked for and having a password prompt popup everytime you start your system would suck.

**Comment by superuser-miguel** [comment]
>  It's an ugly hack
Understated. . .

>  a flatpak without having a password prompt showing every time
Which is why you would need a Portal. Just like OBS used to do before it was fixed to use Portals properly. Also, OBS can use the GPU with VAAPI support. 

I think some more research need to happen, and hope you find a better way of improving your app.

**Comment by dec05eba** [comment]
> > It's an ugly hack
> > Understated. . .
> 
> > a flatpak without having a password prompt showing every time
> 
> Which is why you would need a Portal. Just like OBS used to do before it was fixed to use Portals properly. Also, OBS can use the GPU with VAAPI support.
> 
> I think some more research need to happen, and hope you find a better way of improving your app.

that option only works on wayland, and it has the other limitation I mentioned even on wayland
